# Generated by Django 5.0.6 on 2024-05-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decimal', models.IntegerField()),
                ('biner', models.CharField(max_length=100)),
                ('oktal', models.CharField(max_length=100)),
                ('heksadesimal', models.CharField(max_length=100)),
            ],
        ),
    ]
